[
  {
    "input": "",
    "output": "",
    "states": ["HelloWorld"],
    "task_behavior": {
      
    }
  },

  {
    "input": "",
    "output": "This is a fallback from a custom lambda function exception",
    "states": ["HelloWorld", "CustomErrorFallback"],
    "task_behavior": {
      "FUNCTION_NAME": {"error": "CustomError"}
    }
  },

  {
    "input": "",
    "error": {
      "Error": "States.TaskFailed"
    },
    "states": ["HelloWorld", "ReservedTypeFallback"],
    "task_behavior": {
      "FUNCTION_NAME": {"error": "States.TaskFailed"}
    }
  },

  {
    "input": "",
    "error": {
      "Error": "States.ALL"
    },
    "states": ["HelloWorld", "CatchAllFallback"],
    "task_behavior": {
      "FUNCTION_NAME": {"error": "States.ALL"}
    }
  }
]
